import esbuild from "esbuild";
import process from "process";
import { builtinModules } from 'node:module';
import { readFileSync } from 'fs';

// Inline the pdf.js worker source as a string module so it ships inside main.js (no separate worker file). preview.ts turns it into a blob-URL worker.
const pdfWorkerInline = {
	name: 'pdf-worker-inline',
	setup(build) {
		build.onResolve({ filter: /^pdfjs-worker-inline$/ }, () => ({
			path: 'pdfjs-worker-inline',
			namespace: 'pdf-worker-inline',
		}));
		build.onLoad({ filter: /.*/, namespace: 'pdf-worker-inline' }, () => {
			const code = readFileSync('node_modules/pdfjs-dist/build/pdf.worker.min.mjs', 'utf8');
			return { contents: `export default ${JSON.stringify(code)};`, loader: 'js' };
		});
	},
};

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"child_process",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtinModules],
	format: "cjs",
	target: "es2018",
	plugins: [pdfWorkerInline],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outfile: "main.js",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
