services:
  pipeline:
    build:
      context: .
      labels:
        nope.image-hash: "${NOPE_IMAGE_HASH:-}"
    image: nope
    entrypoint: /app/scripts/build.sh
    volumes:
      - ./app:/app:ro
      - ${VAULT_PATH}:/vault:ro
      - ./build:/build
    working_dir: /build